### ISSUE TITLE
PrivilegesCLI fails to add admin privileges unless logged in

### ISSUE THREAD

**Issue by mnordbye** [SAP/macOS-enterprise-privileges#143]
We've used Privileges with great success until the 2.0 version. Now, we can't longer give admin privileges to a user via terminal/SSH UNLESS it is logged in on the respective computer.

The error message in terminal just says "Failed to change privileges for user xxxxxxx". This works perfectly when we log in that user on the computer itself.

Did anything change in 2.0 to change this behaviour? Is there anything new that needs to be configured for it working remotely? I can't find anything in the documentation.

Worth to note. We use a configuration profile that gets deployed with JAMF, to use the LimitToUser argument. We do this with the provided sample configuration.

**Comment by mthielemann** [comment]
Yes, this is expected behavior. Starting with Privileges 2 the `PrivilegesAgent` is responsible for all the communication with the `PrivilegesDaemon` that actually changes the user's privileges. The `PrivilegesAgent` is launched as soon as a user logs in. If you just access a machine using ssh, the `PrivilegesAgent` is not running and you cannot use `PrivilegesCLI` to change privileges. If you have ssh access to a machine, you could use other tools like `dseditgroup` to achieve this.
