### ISSUE TITLE
[Privileges 2.1] Renew Privileges via Dock Tile

### ISSUE THREAD

**Issue by aduffner** [SAP/macOS-enterprise-privileges#152]
Hi Marc, the following doesn't work like expected during my tests (in german localization). 
- Privileges 2.1.0 (1901)
- macOS 15.2 (24C101)

> `Dock Tile:` Right-click the Dock tile while you have administrator privileges. When the menu appears, hold down the Option key and the menu item "Revoke Privileges" will change to "Renew Privileges". To renew privileges, click the menu item while still holding the Option key.

It remains "Administratorrechte abgeben", after a secondary click on the dock tile while holding the option key afterwards.

**Comment by aduffner** [comment]
<img width="307" alt="Bildschirmfoto 2024-12-12 um 10 02 24" src="https://github.com/user-attachments/assets/0e5ebfef-08e8-4524-933c-18e59e1de8f4" />

**Comment by mthielemann** [comment]
Works here as expected. This option must either be enabled by a profile or you must disable and re-enable it to make the Dock tile aware of it. Because of a bug in macOS 15 I had to build a workaround that only works if the option is managed or has been enabled by the user using the new beta build or higher.

**Comment by aduffner** [comment]
@mthielemann Got it, worked like a charm after I unticked the option in the settings as a user and re-enabled it.
