### ISSUE TITLE
"PrivilegesCLI: Permission denied" in terminal

### ISSUE THREAD

**Issue by mikeym328** [SAP/macOS-enterprise-privileges#29]
We have noticed that after deploying Privileges, when a user opens a new terminal window there is a message right above the prompt that says "PrivilegesCLI: Permission denied".  This happens if the user is admin or standard. What is the cause of this and can it be removed? System: macOS 12.3.1

**Comment by rtrouton** [comment]
I’m unable to reproduce this behavior on my end and it’s not expected behavior. Can you provide more information on how you have Terminal configured?

My suspicion is that there is a shell configuration which is unsuccessfully trying to call the `PrivilegesCLI` command line tool when it opens. For the zsh shell, there are several files which may be referenced (please see https://scriptingosx.com/2019/06/moving-to-zsh-part-2-configuration-files/ for more details) with the most common being the `.zshrc` file in the user’s home directory.

**Comment by mikeym328** [comment]
There is no reference to PrivilegesCLI in the .zshrc files.  The issue seems to be the way the Privileges app was packaged for MDM distribution.  A file is written to /private/etc/paths.d/PrivilegesCLI. If I set the permissions to allow everyone read (or just delete the file) the error goes away.

**Comment by rtrouton** [comment]
Sounds like this issue is addressed then.
