### ISSUE TITLE
Usability: GUI needs to be operable with keyboard alone.

### ISSUE THREAD

**Issue by jannek-aalto** [SAP/macOS-enterprise-privileges#55]
The privileges requester GUI popup defaults to Cancel (a bad assumption, that it's some kind of an accident that the user opens the application) and cannot be "OK"'d without using a mouse; This is a major accessibility/usability issue.

My suggestion would be to default to OK, accept with Enter, close the dialog with Esc. 

Option B, enable the Tab key to switch between OK/Cancel; Escape could/should still cancel.

**Comment by psyrus** [comment]
Would love this as well... It's a small QoL change but makes a big difference to usability

**Comment by Coros** [comment]
This is actually an Apple issue.  Keyboard navigate is disabled by default from Apple.  You can enable it and then utilize tab to navigate the UI. 

`/usr/bin/defaults write NSGlobalDomain AppleKeyboardUIMode -int 2`

**Comment by jannek-aalto** [comment]
**Golden** tip, that; There's even a keyboard shortcut to toggle that accessibility option: **^F7** by default on this Monterey... 

Hitting Return seems to always select the default option regardless of the selection, tapping Space instead works. Esc does nothing. Not optimal, but this trick _is_ more convenient than mousing around.

I still think the default choice is wrong and the UI needs streamlining.

A bit out of scope, but relevant as background; The three-phase dialog is just too much; First one has to respond to an unnecessary question (do you want to) which defaults to a nonsensical answer (Cancel), then type a meaningless minimum-length-limited response and send it, and only then actually authorize the operation. Why? This complexity adds no value. Either you may or may not escalate privileges and that's all there is to it.

**Comment by ewendel** [comment]
Strong plus one on this!

I'd prefer Privileges to remove this step alltogether:

<img width="592" alt="Pasted Graphic" src="https://github.com/SAP/macOS-enterprise-privileges/assets/861483/7629944b-999f-450c-9f53-2374773de7fc">

I mean, I've opened the app, why not prompt me with my password/touch id immediately?

E.g. jumping straight to this one after clicking the app icon:

<img width="370" alt="image" src="https://github.com/SAP/macOS-enterprise-privileges/assets/861483/a268e375-6a82-4fe8-b8f6-d8c2a78e7f32">

That would seem like a more natural interaction to me.

**Comment by hanskhe** [comment]
From a security standpoint, I believe there are good reasons for the existing design.

**Having an initial popup**

Having an initial popup protects from an attack where the adversary tricks the user into placing their finger on the TouchID sensor, and then triggers Priveliges unbeknown to the user. This would cause the user to immediately authenticate and elevate user permissions, as TouchID does not require the placement of the finger on the sensor to happen _after_ the prompt has been issued.

**Cancel as the default option**

If a popup triggers while the user is otherwise engaged, e.g. writing, the default option will most likely be activated, because the user might press space before realising that a popup has appeared. This might be used in a chained attack where the attacker has another exploit to bypass the TouchID prompt, or where the attacker gambles on the user to authenticate anytime the Priveliges popup appears.

**Comment by mthielemann** [comment]
@hanskhe That was exactly what we had in mind when we designed this.
